<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo App</title>
    <link type="text/css" rel="stylesheet" href="css/chooseUser.css">
</head>
<body>
    <form method="GET" action="/homepage">
        <label for="users">Choose a user's todos list list</label>
        <select name="user-id" id="users">

        </select>
    </form>
</body>
</html>