<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo App</title>
    <link type="text/css" rel="stylesheet" href="css/chooseUser.css">
</head>
<body>
    <main>
        <form method="POST" action="/rightUser">
            <label for="users">Choose a user's todos list</label>
            <select name="user_id" id="users">
                <?php
                    if (isset($users)) {
                        echo \Todo\ViewHelpers\DisplayUsers::displayUsers($users);
                    }
                ?>
            </select>
            <input type="submit" value="SEND">
        </form>
        <h4>Add a new User</h4>
        <form method="POST" action="/newUser">
            <label for="userName">Username:</label>
            <input id="userName" type="text" name="username" placeholder="Username...">
            <input type="submit" value="ADD">
        </form>
    </main>
</body>
</html>