<html lang="en">
<head>
    <title>Todo App</title>
    <style>

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        html {
            font-family: sans-serif;
        }

        main {
            width: 50%;
            margin: 0 auto;
        }

        h1 {
            text-align: center;
        }

        section {
            padding: 10px;
            background-color: #FFA500;
        }

        a {
            color: #000000;
            text-decoration: none;
        }

        .todo {
            margin-top: 10px;
            padding: 5px;
            border: 1px solid #000000;
            overflow: auto;
        }

        .description {
            float: left;
            width: 80%;
        }

        .finish-todo {
            float: right;
            width: 20%;
        }

        .finish-todo a {
            float: right;
            border: 1px solid #000000;
            padding: 3px;
            border-radius: 5px;
        }

        h3 {
            margin: 20px 0;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        textarea {
            display: block;
            width: 100%;
            height: 100px;
        }

        input {
            margin-top: 10px;
            background-color: transparent;
            padding: 5px;
            border-radius: 5px;
        }

        .finish-todo form {
            float: right;
        }

        .finish-todo input {
            border: 1px solid #000000;
            padding: 3px;
            border-radius: 5px;
        }

    </style>
</head>
<body>
    <main>
        <section class="todos">
            <h1 class="title">TO DO</h1>
            <?php
                if(isset($todos)) {
                    echo \Todo\ViewHelpers\DisplayTodos::displayTodos($todos);
                }
            ?>
        </section>
        <section class="todos">
            <h1 class="title">Completed</h1>
            <?php
                if(isset($completedTodos)) {
                    echo \Todo\ViewHelpers\DisplayTodos::displayCompletedTodos($completedTodos);
                }
            ?>
        </section>
        <form method="POST" action="homepage/addTodo">
            <h3>Add To do:</h3>
            <label for="description">Description:</label>
            <textarea id="description" name="description" placeholder="To do..."></textarea>
            <label for="date">Date:</label>
            <input id="date" type="date" name="date">
            <input type="submit" value="Add!">
        </form>
    </main>
</body>
</html>